- hosts: all
  become: yes
  tasks:
    # Upgrade packages
    - name: Upgrade packages using yum
      yum:
        name: "*"
        state: latest
        update_cache: yes

    # Check if reboot is required
    - name: Check if system reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    # Reboot the system if needed
    - name: Reboot the system if required
      reboot:
      when: reboot_required.stat.exists
